### ISSUE TITLE
demo-flask ImportError: cannot import name 'Markup' from 'jinja2' 

### ISSUE THREAD

**Issue by fredcy** [onelogin/python3-saml#423]
When I attempt to run the Flask demo it fails immediately:

> ImportError: cannot import name 'Markup' from 'jinja2' (/home/example/test-saml/python3-saml/demo-flask/env/lib/python3.10/site-packages/jinja2/__init__.py)

I'm using Python 3.10.15 and the master branch of python3-saml.  I have not touched any of the files like settings.json yet as I want to get a baseline first. Here are my steps:

```
cd demo-flask
python3 -m venv env
. env/bin/activate
pip install -r requirements.txt
python index.py
```

The ImportError happens immediately.

`pip freeze` shows that I'm getting these packages:

> click==8.1.7
> Flask==1.0
> itsdangerous==2.2.0
> Jinja2==3.1.4
> MarkupSafe==3.0.2
> Werkzeug==3.1.3
>

**Comment by fredcy** [comment]
If I install Flask and python3-saml per the following updated requirements.txt contents, then `python index.py` runs without crashing:

```
flask==3.1.0
python3-saml==1.16.0
```

**Comment by pitbulk** [comment]
I need to adapt the demos to work with python > 3.7 and not vulnerable flask/django/... versions
